### ISSUE TITLE
RangeError when initializing

### ISSUE THREAD

**Issue by borger** [hertzg/node-net-keepalive#16]
Hello,

I've been trying out https://github.com/yungsters/homebridge-mylink for some home automation and I installed it on a Raspberry Pi 3 (environment details below), and I'm getting this error on the net-keepalive dependency or its dependencies (seemengly on the ref-napi), any idea whats going on? 
```
uname -srvio
Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 unknown GNU/Linux
npm -v
6.12.0
node -v
v11.15.0
```

Error message (from homebridge error log):
```
2019-10-21T21:28:59.859Z ref creating a reference to buffer <Buffer , type:
   { size: 0,
     indirection: 1,
     get: [Function: get],
     set: [Function: set],
     name: 'void' }>
2019-10-21T21:28:59.871Z ref allocating Buffer for type with "size" 0
2019-10-21T21:28:59.872Z ref setting value on allocated buffer <Buffer , type:
   { size: 0,
     indirection: 1,
     get: [Function: get],
     set: [Function: set],
     name: 'void' }>
2019-10-21T21:28:59.874Z ref set(): (offset: 0) <Buffer 00 00 00 00, type: { indirection: 2, name: 'void*' }> <Buffer , type:
   { size: 0,
     indirection: 1,
     get: [Function: get],
     set: [Function: set],
     name: 'void' }>
2019-10-21T21:28:59.876Z ref writing pointer to buffer <Buffer 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer , type:
   { size: 0,
     indirection: 1,
     get: [Function: get],
     set: [Function: set],
     name: 'void' }>
2019-10-21T21:28:59.893Z ffi:ffi skipping exporting of non-existant property FFI_UNIX64
2019-10-21T21:28:59.894Z ffi:ffi skipping exporting of non-existant property FFI_WIN64
2019-10-21T21:28:59.894Z ffi:ffi skipping exporting of non-existant property FFI_STDCALL
2019-10-21T21:28:59.894Z ffi:ffi skipping exporting of non-existant property FFI_THISCALL
2019-10-21T21:28:59.895Z ffi:ffi skipping exporting of non-existant property FFI_FASTCALL
2019-10-21T21:28:59.895Z ffi:ffi skipping exporting of non-existant property RTLD_FIRST
2019-10-21T21:28:59.895Z ffi:ffi skipping exporting of non-existant property RTLD_SELF
2019-10-21T21:28:59.895Z ffi:ffi skipping exporting of non-existant property RTLD_MAIN_ONLY
2019-10-21T21:28:59.896Z ffi:ffi skipping exporting of non-existant property FFI_MS_CDECL
2019-10-21T21:28:59.902Z ref:struct defining new struct "type"
2019-10-21T21:28:59.903Z ref:struct defining new struct type field size
2019-10-21T21:28:59.905Z ref:struct defining new struct type field alignment
2019-10-21T21:28:59.907Z ref:struct additional padding to the end of struct: 2
2019-10-21T21:28:59.907Z ref:struct defining new struct type field type
2019-10-21T21:28:59.908Z ref:struct defining new struct type field elements
2019-10-21T21:28:59.923Z ffi:ForeignFunction creating new ForeignFunction <Buffer@0x76f83be4 >
2019-10-21T21:28:59.925Z ffi:cif creating `ffi_cif *` instance
2019-10-21T21:28:59.927Z ffi:types Type() void*
2019-10-21T21:28:59.927Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.927Z ffi:types Type() CString
2019-10-21T21:28:59.928Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.928Z ref writing pointer to buffer <Buffer@0x31b6a80 00 00 00 00 00 00 00 00> 0 <Buffer@0x742482d8 , name: 'pointer'>
2019-10-21T21:28:59.929Z ffi:types Type() int
2019-10-21T21:28:59.929Z ffi:types returning `ffi_type` int
2019-10-21T21:28:59.930Z ref writing pointer to buffer <Buffer@0x31b6a80 d8 82 24 74 00 00 00 00, [Symbol(attached)]: [ <Buffer@0x742482d8 , name: 'pointer'> ]> 4 <Buffer@0x742482fc , name: 'int'>
2019-10-21T21:28:59.932Z ffi:cif no ABI specified (this is OK), using FFI_DEFAULT_ABI
2019-10-21T21:28:59.933Z ffi:_ForeignFunction creating new ForeignFunction <Buffer@0x76f83be4 >
2019-10-21T21:28:59.934Z ffi:ForeignFunction creating new ForeignFunction <Buffer@0x76f83c6c >
2019-10-21T21:28:59.935Z ffi:cif creating `ffi_cif *` instance
2019-10-21T21:28:59.935Z ffi:types Type() int
2019-10-21T21:28:59.935Z ffi:types returning `ffi_type` int
2019-10-21T21:28:59.935Z ffi:types Type() void*
2019-10-21T21:28:59.936Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.936Z ref writing pointer to buffer <Buffer@0x31b6a58 00 00 00 00> 0 <Buffer@0x742482d8 , name: 'pointer'>
2019-10-21T21:28:59.937Z ffi:cif no ABI specified (this is OK), using FFI_DEFAULT_ABI
2019-10-21T21:28:59.937Z ffi:_ForeignFunction creating new ForeignFunction <Buffer@0x76f83c6c >
2019-10-21T21:28:59.938Z ffi:ForeignFunction creating new ForeignFunction <Buffer@0x76f83cc8 >
2019-10-21T21:28:59.938Z ffi:cif creating `ffi_cif *` instance
2019-10-21T21:28:59.938Z ffi:types Type() void*
2019-10-21T21:28:59.938Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.939Z ffi:types Type() void*
2019-10-21T21:28:59.939Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.939Z ref writing pointer to buffer <Buffer@0x31b6a68 00 00 00 00 00 00 00 00> 0 <Buffer@0x742482d8 , name: 'pointer'>
2019-10-21T21:28:59.940Z ffi:types Type() CString
2019-10-21T21:28:59.940Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.940Z ref writing pointer to buffer <Buffer@0x31b6a68 d8 82 24 74 00 00 00 00, [Symbol(attached)]: [ <Buffer@0x742482d8 , name: 'pointer'> ]> 4 <Buffer@0x742482d8 , name: 'pointer'>
2019-10-21T21:28:59.941Z ffi:cif no ABI specified (this is OK), using FFI_DEFAULT_ABI
2019-10-21T21:28:59.941Z ffi:_ForeignFunction creating new ForeignFunction <Buffer@0x76f83cc8 >
2019-10-21T21:28:59.942Z ffi:ForeignFunction creating new ForeignFunction <Buffer@0x76f83f6c >
2019-10-21T21:28:59.942Z ffi:cif creating `ffi_cif *` instance
2019-10-21T21:28:59.943Z ffi:types Type() CString
2019-10-21T21:28:59.943Z ffi:types returning `ffi_type` pointer
2019-10-21T21:28:59.943Z ffi:cif no ABI specified (this is OK), using FFI_DEFAULT_ABI
2019-10-21T21:28:59.943Z ffi:_ForeignFunction creating new ForeignFunction <Buffer@0x76f83f6c >
2019-10-21T21:28:59.949Z ffi:ForeignFunction creating new ForeignFunction <Buffer@0x74239518 >
2019-10-21T21:28:59.949Z ffi:cif creating `ffi_cif *` instance
2019-10-21T21:28:59.950Z ffi:types Type() int
2019-10-21T21:28:59.950Z ffi:types returning `ffi_type` int
2019-10-21T21:28:59.950Z ffi:cif no ABI specified (this is OK), using FFI_DEFAULT_ABI
2019-10-21T21:28:59.950Z ffi:_ForeignFunction creating new ForeignFunction <Buffer@0x74239518 >
2019-10-21T21:28:59.953Z ffi:Library creating Library object for null
2019-10-21T21:28:59.954Z ffi:DynamicLibrary new DynamicLibrary() null 2
2019-10-21T21:28:59.955Z ffi:_ForeignFunction invoking proxy function
2019-10-21T21:28:59.956Z ref allocating Buffer for type with "size" 4
2019-10-21T21:28:59.957Z ref setting value on allocated buffer null
[10/21/2019, 6:28:59 PM] ====================
[10/21/2019, 6:28:59 PM] ERROR LOADING PLUGIN homebridge-mylink:
[10/21/2019, 6:28:59 PM] RangeError: error setting argument 1 - Invalid count value
    at String.repeat (<anonymous>)
    at reduceToSingleString (internal/util/inspect.js:1365:27)
    at formatRaw (internal/util/inspect.js:791:15)
    at formatValue (internal/util/inspect.js:529:10)
    at formatProperty (internal/util/inspect.js:1266:11)
    at getOwnNonIndexProperties.reduce (buffer.js:682:19)
    at Array.reduce (<anonymous>)
    at Buffer.inspect (buffer.js:679:51)
    at Buffer.refinspect (/usr/local/lib/node_modules/homebridge-mylink/node_modules/net-keepalive/node_modules/ref-napi/lib/ref.js:1467:23)
    at formatValue (internal/util/inspect.js:511:31)
[10/21/2019, 6:28:59 PM] ====================
2019-10-21T21:29:00.598Z serialport:binding:auto-detect loading LinuxBinding
Mon, 21 Oct 2019 21:29:00 GMT express:application set "x-powered-by" to true
Mon, 21 Oct 2019 21:29:00 GMT express:application set "etag" to 'weak'
Mon, 21 Oct 2019 21:29:00 GMT express:application set "etag fn" to [Function: generateETag]
Mon, 21 Oct 2019 21:29:00 GMT express:application set "env" to 'development'
Mon, 21 Oct 2019 21:29:00 GMT express:application set "query parser" to 'extended'
Mon, 21 Oct 2019 21:29:00 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
Mon, 21 Oct 2019 21:29:00 GMT express:application set "subdomain offset" to 2
Mon, 21 Oct 2019 21:29:00 GMT express:application set "trust proxy" to false
Mon, 21 Oct 2019 21:29:00 GMT express:application set "trust proxy fn" to [Function: trustNone]
Mon, 21 Oct 2019 21:29:00 GMT express:application booting in development mode
Mon, 21 Oct 2019 21:29:00 GMT express:application set "view" to [Function: View]
Mon, 21 Oct 2019 21:29:00 GMT express:application set "views" to '/var/homebridge/views'
Mon, 21 Oct 2019 21:29:00 GMT express:application set "jsonp callback name" to 'callback'
2019-10-21T21:29:02.506Z serialport:binding:auto-detect loading LinuxBinding
[10/21/2019, 6:29:03 PM] Error: The requested platform 'Somfy myLink' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

Thanks in advance!

**Comment by hertzg** [comment]
There are multiple layers before it reaches `net-keepalive`, I don't think this error is in any way related to the functionality of this module. Seems more like some kind of string formatting issue.

I can't really help with this as it is not an issue on this side. Try asking in homebridge community first. If you can provide a code example to demonstrate any issue I'd be glad to fix if you can reproduce it.

Closing this for now, feel free to comment here with the code example.

**Comment by borger** [comment]
will do @hertzg thank you!

**Comment by hertzg** [comment]
@all-contributors please add @borger for bug
