### ISSUE TITLE
got some error when installing

### ISSUE THREAD

**Issue by selient** [hertzg/node-net-keepalive#6]
got some error when installing 

my environment:
```
uname -srvio
Linux 4.9.58-18.55.amzn1.x86_64 #1 SMP Thu Nov 2 04:38:47 UTC 2017 x86_64 GNU/Linux
npm -v
5.5.1
node -v
v9.0.0
```
Error message:

```
> ref@1.3.3 install /home/this/project/node_modules/net-keepalive/node_modules/ref
> node-gyp rebuild

make: Entering directory `/home/this/project/node_modules/net-keepalive/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:64: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/this/.node-gyp/9.0.0/include/node/v8.h:3114): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/home/this/project/node_modules/net-keepalive/node_modules/ref/build'

> ffi@2.2.0 install /home/this/project/node_modules/net-keepalive/node_modules/ffi
> node-gyp rebuild

make: Entering directory `/home/this/project/node_modules/net-keepalive/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/ffi.h:23,
                 from ../src/ffi.cc:3:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:64: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/this/.node-gyp/9.0.0/include/node/v8.h:3114): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
../src/ffi.cc: In static member function ‘static void FFI::InitializeBindings(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/ffi.cc:111:153: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                         ^
../src/ffi.cc:111:153: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:114:159: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), WrapPointer((char *)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                               ^
../src/ffi.cc:114:159: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:123:167: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                                                       ^
../src/ffi.cc:123:167: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:124:171: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_sarg)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                                           ^
../src/ffi.cc:124:171: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:125:171: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                                           ^
../src/ffi.cc:125:171: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:126:169: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                                         ^
../src/ffi.cc:126:169: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/ffi.cc:132:148: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t, v8::PropertyAttribute)’
   target->ForceSet(Nan::New<String>("HAS_OBJC").ToLocalChecked(), Nan::New<Boolean>(hasObjc), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                                                    ^
../src/ffi.cc:132:148: note: candidate is:
In file included from /home/this/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/this/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/this/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/this/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory `/home/this/project/node_modules/net-keepalive/node_modules/ffi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/this/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.58-18.55.amzn1.x86_64
gyp ERR! command "/home/this/.nvm/versions/node/v9.0.0/bin/node" "/home/this/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/this/project/node_modules/net-keepalive/node_modules/ffi
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ingics-igs-rchost@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/this/.npm/_logs/2018-03-22T02_08_52_018Z-debug.log

```

**Comment by hertzg** [comment]
Looks like an `node-ffi` issue to me.

**Comment by hertzg** [comment]
Yes this is a `node-ffi` issue. Theres not much I can do unless they fix it.

/ref https://github.com/node-ffi/node-ffi/issues/468

**Comment by hertzg** [comment]
Closing this for now

**Comment by hertzg** [comment]
@all-contributors please add @selient for bug
